# Generated by Django 4.0.1 on 2022-01-14 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Investor name', max_length=255)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, help_text="Remaining investor's amount.", max_digits=11)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text="Total investor's amount.", max_digits=11)),
                ('individual_amount', models.DecimalField(decimal_places=2, help_text='Individual amount per project', max_digits=11)),
                ('project_delivery_deadline', models.DateField(help_text='Deadline that funded projects must deliver by')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the project', max_length=255, verbose_name="Project's name")),
                ('description', models.TextField(help_text='What’s the goal of the project?', max_length=700)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total project funding required', max_digits=7)),
                ('delivery_date', models.DateField(help_text='Estimated project delivery date.')),
                ('funded', models.BooleanField(default=False, editable=False)),
                ('funded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funded_projects', to='core.investor')),
            ],
        ),
    ]
